# Generated by Django 4.2.3 on 2023-07-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name=['culturedUnicorn8'])),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='blob_pics')),
            ],
        ),
    ]
