# Generated by Django 4.2.3 on 2023-07-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(default=['cruelMuesli6'], max_length=200),
        ),
    ]
